 version: 2
 jobs:
   build:
     docker:
       - image: circleci/python:3.7
     steps:
       - checkout
       - run: pip install --user -r requirements.txt
       - run: nosetests --with-coverage
